### ISSUE TITLE
twolevel_dbm.py and 1level

### ISSUE THREAD

**Issue by weimath** [CoBrALab/twolevel_ants_dbm#56]
for 'python twolevel_dbm.py 1level t1.csv

```
-----------------------------------------------------------
twolevel_dbm.py: Running Second-Level Modelbuild

--------------------------------------------------------------------------------------
 Creating template output/secondlevel/secondlevel_template0.nii.gz from a population average image from the inputs.
 /mnt/hgfs/data_chen/data_3DT1/BD_003_tanbowen/coTanBowen12.niiii
--------------------------------------------------------------------------------------
/opt/ANTs/bin//antsMultivariateTemplateConstruction2.sh: line 272:  8928 Segmentation fault      (core dumped) ${ANTSPATH}/AverageImages $dim $output 1 ${images[*]}
Your initial template : output/secondlevel/secondlevel_template0.nii.gz[0 ] was not created.  This indicates trouble!  You may want to check correctness of your input parameters. exiting.

Subprocess Error on command antsMultivariateTemplateConstruction2.sh -d 3 -o output/secondlevel/secondlevel_ -r 1 -l 1 -y 0 -c 0 -a 1 -e 1 -g 0.25 -i 4 -n 0 -m CC[4] -t SyN -u 20:00:00 -v 8gb -q 100x100x70x20 -f 6x4x2x1 -s 3x2x1x0 t1.csv  && echo DONE > output/secondlevel/COMPLETE
```

**Comment by gdevenyi** [comment]
In order to provide any support, you will need to provide
1. How you installed ANTs
2. The type of files you are inputting
3. The exact command  you're using

**Comment by gdevenyi** [comment]
This looks wrong:
```
 /mnt/hgfs/data_chen/data_3DT1/BD_003_tanbowen/coTanBowen12.niiii
```

I'm pretty sure there's not that many "i" in `nii`

**Comment by weimath** [comment]
> In order to provide any support, you will need to provide
> 
> 1. How you installed ANTs
> 2. The type of files you are inputting
> 3. The exact command  you're using

1, installed ANTs by    https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS
2,  like this:

> /mnt/hgfs/data_chen/data_3DT1/s_002/s002.nii.gz
>/mnt/hgfs/data_chen/data_3DT1/s_003/s003.nii.gz

   in .csv file
3,  **python twolevel_dbm.py 1level t1.csv**     
 I use this command, and error is : 

> Segmentation fault (core dumped)
> 
> Subprocess Error on command PrintHeader /mnt/hgfs/data_chen/data_3DT1/s_002/s002.nii.gz 1

![image](https://user-images.githubusercontent.com/16069593/98227822-b9556600-1f92-11eb-9d37-40703dc90275.png)

![image](https://user-images.githubusercontent.com/16069593/98227946-e570e700-1f92-11eb-9679-3f3aac14bf96.png)

**Comment by weimath** [comment]
![image](https://user-images.githubusercontent.com/16069593/98250020-ea915e80-1fb1-11eb-9439-779509492f40.png)

when run 2level, 2 hours has past, but at 0%.

please, thkans!

**Comment by gdevenyi** [comment]
This is a crash of the ANTs tools and has nothing to do with twolevel_dbm.py.
```
Subprocess Error on command PrintHeader /mnt/hgfs/data_chen/data_3DT1/s_002/s002.nii.gz 1
```
I cannot assist with a broken ANTs install.



> when run 2level, 2 hours has past, but at 0%.

1. You did not share "t2.csv" contents.
2. antsMultivariateTemplateConstruction2.sh is computationally expensive and with your current configuration you are running a serial subject-wise run based on the output. The output will update when a subject-wise model build completes.

**Comment by weimath** [comment]
Thanks for your reply.

**Comment by weimath** [comment]
Dear Prof,
Ps: for "t_dbm.py", I just change name from "twolevel_dbm.py"
but “antsMultivariateTemplateConstruction2.sh” could run normally

![image](https://user-images.githubusercontent.com/16069593/99227473-4071cc00-2826-11eb-852d-e44b18f42133.png)
![image](https://user-images.githubusercontent.com/16069593/99227543-58e1e680-2826-11eb-9b11-122f20623d83.png)

**Comment by weimath** [comment]
Dear Prof, Could you share me your a result file about  jacobians files, Please, thank you very much.

**Comment by gdevenyi** [comment]
Something is wrong with your CSV file:
![image](https://user-images.githubusercontent.com/3001850/99278579-3a1b2a00-27fd-11eb-8b59-848a0badd7ea.png)

Guesses
1. Non-ascii characters
2. Non Unix line endings
3. Not actually a plain text csv file


> Dear Prof, Could you share me your a result file about jacobians files, Please, thank you very much.

I don't understand the question.

**Comment by weimath** [comment]
> 2. Non Unix line endings
 
I got it! thank you very much!

**Comment by weimath** [comment]
result like this
*_absolute_smooth0.8493218002880191.nii.gz
![image](https://user-images.githubusercontent.com/16069593/99394606-20bbd000-291a-11eb-8bb2-d9d3a06e1379.png)

 I'm not sure if it's right? It looks weird

**Comment by gdevenyi** [comment]
The outputs a smoothed jacobians. Please see the documentation here: https://github.com/CoBrALab/twolevel_ants_dbm#outputs
