### ISSUE TITLE
ANTs Subprocess Error

### ISSUE THREAD

**Issue by shlrley** [CoBrALab/twolevel_ants_dbm#58]
Hi,

I'm running the ANTs procedure on 543 subjects. It has been going well, but I ran into an error where it says that the directory "output/jacobians/resampled/COMPLETE" cannot be found. 

It looks like the only directory inside of my output/jacobians directory is one called "overall"

Please see the contents of **my-dbm-run-script.sh** here:
[my-dbm-run-script.sh.zip](https://github.com/CoBrALab/twolevel_ants_dbm/files/5972862/my-dbm-run-script.sh.zip)

Here are the contents of **dbm_logfile.log**:
[dbm_logfile.log](https://github.com/CoBrALab/twolevel_ants_dbm/files/5972864/dbm_logfile.log)

**Comment by gdevenyi** [comment]
Please update your copy of twolevel_dbm with `git pull` and run again.

**Comment by shlrley** [comment]
It works now, thank you so much!

**Comment by gdevenyi** [comment]
This was either a random issue or a out-of-order race condition in directory creation. I have moved all the directory creation to the top of the function to avoid this in the future.
